#!/usr/bin/env python3
# generate src/lib/coff/tables.mach from tools/coff/tables.txt.
#
# run by hand from anywhere: python3 tools/coff/gen-tables.py, then
# mach fmt src/lib/coff/tables.mach. the build never runs this, and the output
# is deterministic. every row is checked: a table opens before its rows, a name
# is unique, a value fits in 64 bits, and every row cites a source.

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TXT = os.path.join(HERE, "tables.txt")
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
OUT = os.path.join(ROOT, "src", "lib", "coff", "tables.mach")

MASK64 = (1 << 64) - 1
NAME = re.compile(r"^[A-Z][A-Z0-9_]*$")


def fail(lineno, msg):
    sys.exit("gen-tables: %s:%d: %s" % (TXT, lineno, msg))


def parse_value(text, lineno):
    m = re.match(r"^(-?)(0x[0-9A-Fa-f]+|\d+)$", text)
    if not m:
        fail(lineno, "bad value %r" % text)
    n = int(m.group(2), 0)
    if m.group(1):
        n = -n
    if n < -(1 << 63) or n > MASK64:
        fail(lineno, "value %r does not fit 64 bits" % text)
    return n & MASK64


def parse():
    tables = []
    by_table = {}
    names = set()
    with open(TXT, encoding="utf-8") as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.rstrip("\n")
            if not line.strip() or line.startswith("#"):
                continue
            if line.startswith("table "):
                parts = line.split(" ", 2)
                if len(parts) != 3 or not NAME.match(parts[1]):
                    fail(lineno, "bad table line")
                if parts[1] in by_table:
                    fail(lineno, "table %s declared twice" % parts[1])
                tables.append((parts[1], parts[2]))
                by_table[parts[1]] = []
                continue
            parts = line.split(" ", 3)
            if len(parts) != 4:
                fail(lineno, "row needs table, name, value and source")
            table, name, value, source = parts
            if not tables or tables[-1][0] != table:
                fail(lineno, "row of %s outside its table" % table)
            if not NAME.match(name):
                fail(lineno, "bad name %r" % name)
            if name in names:
                fail(lineno, "name %s appears twice" % name)
            if not source.strip() or '"' in source or "\\" in source:
                fail(lineno, "bad source for %s" % name)
            names.add(name)
            by_table[table].append((name, parse_value(value, lineno), source.strip()))
    for table, _ in tables:
        if not by_table[table]:
            sys.exit("gen-tables: table %s has no rows" % table)
    return tables, by_table


HEADER = """# the PE/COFF constant tables, generated by tools/coff/gen-tables.py
# from tools/coff/tables.txt, which cites the PE Format specification and
# Wine's winnt.h and winuser.h at commit d38598c894f6.

use std.types.bool.bool;
use std.types.bool.false;
use std.types.bool.true;
use std.types.option.opt;
use std.types.size.usize;
use std.types.string.str;
use std.types.string.str_equals;

# one named constant: its name as the specification spells it, its value and
# the source that defines it. a signed value holds its 64-bit two's complement,
# so a field of narrower width compares against the value truncated to that width
pub rec Constant {
    name:   str;
    value:  u64;
    source: str;
}

# a table: the number of rows and where the first one lives
pub rec Set {
    count: usize;
    rows:  **Constant;
}
"""

LOOKUPS = """
pub fun name_of(s: *Set, value: u64) opt[*Constant] {
    var i: usize = 0;
    for (i < s.count) {
        if (s.rows[i].value == value) { ret opt[*Constant].some{s.rows[i]}; }
        i = i + 1;
    }
    ret opt[*Constant].none{};
}

pub fun by_name(s: *Set, name: str) opt[*Constant] {
    var i: usize = 0;
    for (i < s.count) {
        if (str_equals(s.rows[i].name, name)) { ret opt[*Constant].some{s.rows[i]}; }
        i = i + 1;
    }
    ret opt[*Constant].none{};
}

# one recorded constant of a source list
rec Expect {
    name:  str;
    value: u64;
}

# the table holds exactly the n recorded constants, each under its name with its
# value, each name once, and both lookups find every row
fun walk(s: *Set, want: *Expect, n: usize) bool {
    if (s.count != n) { ret false; }
    var i: usize = 0;
    for (i < n) {
        val got: opt[*Constant] = by_name(s, want[i].name);
        if (sel got.none)                    { ret false; }
        if (got.some.value != want[i].value) { ret false; }
        i = i + 1;
    }
    i = 0;
    for (i < n) {
        val row: *Constant = s.rows[i];
        var j:   usize     = 0;
        for (j < n) {
            if (j != i && str_equals(s.rows[j].name, row.name)) { ret false; }
            j = j + 1;
        }
        val named: opt[*Constant] = by_name(s, row.name);
        if (sel named.none)    { ret false; }
        if (named.some != row) { ret false; }
        val valued: opt[*Constant] = name_of(s, row.value);
        if (sel valued.none)                { ret false; }
        if (valued.some.value != row.value) { ret false; }
        i = i + 1;
    }
    ret true;
}
"""


def emit(tables, by_table):
    out = [HEADER]
    for table, desc in tables:
        rows = by_table[table]
        out.append("# %s" % desc)
        for name, value, source in rows:
            out.append('pub val %s: Constant = Constant{name: "%s", value: 0x%x, source: "%s"};'
                       % (name, name, value, source))
        out.append("val %s_ROWS: [%d]*Constant = [%d]*Constant{" % (table, len(rows), len(rows)))
        for name, _, _ in rows:
            out.append("    ?%s," % name)
        out.append("};")
        out.append("pub val %s: Set = Set{count: %d, rows: ?%s_ROWS[0]};" % (table, len(rows), table))
        out.append("")
    out.append(LOOKUPS.lstrip("\n"))
    for table, _ in tables:
        rows = by_table[table]
        out.append("val %s_WANT: [%d]Expect = [%d]Expect{" % (table, len(rows), len(rows)))
        for name, value, _ in rows:
            out.append('    Expect{name: "%s", value: 0x%x},' % (name, value))
        out.append("};")
        out.append("")
    out.append("test tables__rows_match_source {")
    for table, _ in tables:
        out.append("    if (!walk(?%s, ?%s_WANT[0], %d))  { ret 1; }" % (table, table, len(by_table[table])))
    out.append("    ret 0;")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    tables, by_table = parse()
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(emit(tables, by_table))
    print("wrote %s: %d tables, %d rows" % (OUT, len(tables), sum(len(r) for r in by_table.values())))


if __name__ == "__main__":
    main()
