#!/usr/bin/env python3
# generate src/lib/macho/tables.mach from tools/macho/constants.txt.
#
# run by hand from anywhere: python3 tools/macho/gen-tables.py
# the build never runs this. the output is deterministic, and the one walk
# test checks every table against the same recorded rows.

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))
DATA = os.path.join(HERE, "constants.txt")
OUT = os.path.join(ROOT, "src", "lib", "macho", "tables.mach")

HEX = re.compile(r"^0x[0-9a-f]+$")
TEXT = re.compile(r'^"[^"\\]*"$')
IDENT = re.compile(r"^[A-Za-z][A-Za-z0-9_]*$")


def parse(path):
    tables = []      # {kind, name, header, doc, rows: [(name, text)]}
    excludes = []    # (name, reason)
    doc = ""
    cur = None
    for n, raw in enumerate(open(path, encoding="utf-8"), 1):
        line = raw.rstrip("\n")
        if not line.strip():
            doc, cur = "", None
            continue
        if line.startswith("#"):
            doc = line[1:].strip()
            continue
        head = line.split()
        if head[0] in ("table", "text"):
            if len(head) != 3:
                raise SystemExit("%s:%d: %s NAME HEADER expected" % (path, n, head[0]))
            cur = {"kind": head[0], "name": head[1], "header": head[2], "doc": doc, "rows": []}
            tables.append(cur)
            doc = ""
        elif head[0] == "exclude":
            excludes.append((head[1], " ".join(head[2:])))
            cur = None
        else:
            if cur is None:
                raise SystemExit("%s:%d: row outside a table" % (path, n))
            if len(head) != 2:
                raise SystemExit("%s:%d: NAME VALUE expected" % (path, n))
            name, value = head
            if cur["kind"] == "table" and not HEX.match(value):
                raise SystemExit("%s:%d: hex value expected, got %s" % (path, n, value))
            if cur["kind"] == "text" and not TEXT.match(line.split(" ", 1)[1]):
                raise SystemExit("%s:%d: quoted text expected" % (path, n))
            if not IDENT.match(name):
                raise SystemExit("%s:%d: bad name %s" % (path, n, name))
            cur["rows"].append((name, line.split(" ", 1)[1]))
    return tables, excludes


def check(tables, excludes):
    names, sets = {}, {}
    for t in tables:
        if t["name"] in sets:
            raise SystemExit("table %s is named twice" % t["name"])
        sets[t["name"]] = t
        if not t["rows"]:
            raise SystemExit("table %s has no rows" % t["name"])
        for name, _ in t["rows"]:
            if name in names:
                raise SystemExit("constant %s is in two tables" % name)
            names[name] = t["name"]
    for name, _ in excludes:
        if name in names:
            raise SystemExit("constant %s is both a row and excluded" % name)
    for name in names:
        if name in sets:
            raise SystemExit("constant %s shares a name with a table" % name)


def block(lines):
    """align a run of `pub val`/`val` declarations the way mach fmt does."""
    name_w = max(len(name) + 1 for _, name, _, _ in lines)
    type_w = max(len(ty) for _, _, ty, _ in lines)
    out = []
    for prefix, name, ty, body in lines:
        out.append("%s%s %s = %s" % (prefix.ljust(8), (name + ":").ljust(name_w), ty.ljust(type_w), body))
    return out


def emit_table(t):
    kind = t["kind"]
    rec = "Constant" if kind == "table" else "TextConstant"
    set_ty = "Set" if kind == "table" else "TextSet"
    rows = t["rows"]
    n = len(rows)
    out = ["# %s" % t["doc"]]
    decls = []
    for name, val in rows:
        if kind == "table":
            body = '%s{name: "%s", value: %s, source: "%s"};' % (rec, name, val, t["header"])
        else:
            body = '%s{name: "%s", text: %s, source: "%s"};' % (rec, name, val, t["header"])
        decls.append(("pub val", name, rec, body))
    rows_name = t["name"] + "_ROWS"
    refs = ["    ?%s," % name for name, _ in rows]
    decls.append(("val", rows_name, "[%d]*%s" % (n, rec), "[%d]*%s{" % (n, rec)))
    out += block(decls)
    out += refs
    out.append("};")
    out.append("pub val %s: %s = %s{count: %d, rows: ?%s[0]};" % (t["name"], set_ty, set_ty, n, rows_name))
    return out


def emit_want(t):
    kind = t["kind"]
    n = len(t["rows"])
    out = []
    if kind == "table":
        out.append("val %s_WANT: [%d]Expect = [%d]Expect{" % (t["name"], n, n))
        for name, val in t["rows"]:
            out.append('    Expect{name: "%s", value: %s},' % (name, val))
    else:
        out.append("val %s_WANT: [%d]ExpectText = [%d]ExpectText{" % (t["name"], n, n))
        for name, val in t["rows"]:
            out.append('    ExpectText{name: "%s", text: %s},' % (name, val))
    out.append("};")
    return out


HEADER = """# the Mach-O constant tables, generated by tools/macho/gen-tables.py from
# tools/macho/constants.txt. every value is the one the stated SDK header
# declares, at the revision src/lib/macho.mach names for that header. one
# table per enumeration, so a value is named in its own enumeration.

use std.types.bool.bool;
use std.types.bool.false;
use std.types.bool.true;
use std.types.option.opt;
use std.types.size.usize;
use std.types.string.str;
use std.types.string.str_equals;

# one named constant: its name as the header spells it, its value and the
# header it comes from
pub rec Constant {
    name:   str;
    value:  u64;
    source: str;
}

# a table: the number of rows and where the first one lives
pub rec Set {
    count: usize;
    rows:  **Constant;
}

# one named string constant: its name, its text and the header it comes from
pub rec TextConstant {
    name:   str;
    text:   str;
    source: str;
}

# a table of string constants
pub rec TextSet {
    count: usize;
    rows:  **TextConstant;
}
"""

LOOKUPS = """# the constant a table holds under a value, the first one when values are shared
pub fun name_of(s: *Set, value: u64) opt[*Constant] {
    var i: usize = 0;
    for (i < s.count) {
        if (s.rows[i].value == value) { ret opt[*Constant].some{s.rows[i]}; }
        i = i + 1;
    }
    ret opt[*Constant].none{};
}

# the constant a table holds under a name
pub fun by_name(s: *Set, name: str) opt[*Constant] {
    var i: usize = 0;
    for (i < s.count) {
        if (str_equals(s.rows[i].name, name)) { ret opt[*Constant].some{s.rows[i]}; }
        i = i + 1;
    }
    ret opt[*Constant].none{};
}

# the string constant a table holds under a name
pub fun text_by_name(s: *TextSet, name: str) opt[*TextConstant] {
    var i: usize = 0;
    for (i < s.count) {
        if (str_equals(s.rows[i].name, name)) { ret opt[*TextConstant].some{s.rows[i]}; }
        i = i + 1;
    }
    ret opt[*TextConstant].none{};
}
"""

TESTS = """
# one recorded constant of a source list
rec Expect {
    name:  str;
    value: u64;
}

# one recorded string constant of a source list
rec ExpectText {
    name: str;
    text: str;
}

# the table holds exactly the n recorded constants, each under its name with its
# value, each name once, and both lookups find every row
fun walk(s: *Set, want: *Expect, n: usize) bool {
    if (s.count != n) { ret false; }
    var i: usize = 0;
    for (i < n) {
        val got: opt[*Constant] = by_name(s, want[i].name);
        if (sel got.none)                    { ret false; }
        if (got.some.value != want[i].value) { ret false; }
        i = i + 1;
    }
    i = 0;
    for (i < n) {
        val row: *Constant = s.rows[i];
        var j:   usize     = 0;
        for (j < n) {
            if (j != i && str_equals(s.rows[j].name, row.name)) { ret false; }
            j = j + 1;
        }
        val named: opt[*Constant] = by_name(s, row.name);
        if (sel named.none)    { ret false; }
        if (named.some != row) { ret false; }
        val valued: opt[*Constant] = name_of(s, row.value);
        if (sel valued.none)                { ret false; }
        if (valued.some.value != row.value) { ret false; }
        i = i + 1;
    }
    ret true;
}

# the string table holds exactly the n recorded string constants, each under its
# name with its text, each name once
fun walk_text(s: *TextSet, want: *ExpectText, n: usize) bool {
    if (s.count != n) { ret false; }
    var i: usize = 0;
    for (i < n) {
        val got: opt[*TextConstant] = text_by_name(s, want[i].name);
        if (sel got.none)                             { ret false; }
        if (!str_equals(got.some.text, want[i].text)) { ret false; }
        i = i + 1;
    }
    i = 0;
    for (i < n) {
        var j: usize = 0;
        for (j < n) {
            if (j != i && str_equals(s.rows[j].name, s.rows[i].name)) { ret false; }
            j = j + 1;
        }
        val named: opt[*TextConstant] = text_by_name(s, s.rows[i].name);
        if (sel named.none)          { ret false; }
        if (named.some != s.rows[i]) { ret false; }
        i = i + 1;
    }
    ret true;
}

"""


def emit_test(tables):
    lines = []
    for t in tables:
        fn = "walk" if t["kind"] == "table" else "walk_text"
        want = "%s_WANT[0]" % t["name"]
        call = "if (!%s(?%s, ?%s, %d))" % (fn, t["name"], want, len(t["rows"]))
        lines.append((call, t["name"]))
    width = max(len(c) for c, _ in lines)
    return ["    %s { ret 1; }" % c.ljust(width) for c, _ in lines] + ["    ret 0;", "}"]


def main():
    tables, excludes = parse(DATA)
    check(tables, excludes)
    chunks = [HEADER.rstrip("\n"), LOOKUPS.rstrip("\n")]
    for t in tables:
        chunks.append("\n".join(emit_table(t)))
    chunks.append("\n".join(sum((emit_want(t) + [""] for t in tables), [])).rstrip("\n"))
    chunks.append(TESTS.strip("\n"))
    chunks.append("test tables__rows_match_source {\n" + "\n".join(emit_test(tables)))
    text = "\n\n".join(chunks) + "\n"
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote %s: %d tables, %d constants" % (OUT, len(tables), sum(len(t["rows"]) for t in tables)))


if __name__ == "__main__":
    main()
